name: RamanaReddy-github-actions
run-name: '${{ github.actor }} is learning GitHub Actions'

on: 
  push:

jobs:
  compile-code:
    name: Compiling The Code
    runs-on: ubuntu-latest
    steps:
      - name: Boda Triggering
        run: mvn clean test -Pqa
